### ISSUE TITLE
wrong field name used Synonym, should be synonym

### ISSUE THREAD

**Issue by zhuomingao** [NCIOCPL/bestbets-api#13]
During integration testing, I found that the indexer uses wrong field name, should be synonym, but Synonym is used in 

bestbets-api\src\NCI.OCPL.Api.BestBets\Models\BestBetsMatch.cs

all other field names are lower case except Synonym.

This is causing the bestbet search returning nothing for any given keywords.

**Comment by blairlearn** [comment]
This has been completed.  @zhuomingao , please verify.

**Comment by zhuomingao** [comment]
verified and results look good.
