### ISSUE TITLE
index optimize reports error for ES cluster with multiple nodes

### ISSUE THREAD

**Issue by zhuomingao** [NCIOCPL/bestbets-api#16]
For ES cluster with multiple nodes, after index optimize is successfully done, the indexer should not throw exception:  Error Optimizing index,bestbetspreview20170131143502 optimize finished unexpected response

The problem is in 
https://github.com/NCIOCPL/bestbets-api/blob/master/src/NCI.OCPL.Api.BestBets.Indexer/Services/ESBBIndexerService.cs

if (
                response.Shards.Total != 1 
                || response.Shards.Successful != 1 
                || response.Shards.Failed != 0
            )
            {
                throw new Exception("Error Optimizing index," + indexName + " optimize finished unexpected response");
            }

It checks shards.total, but for a successful optimize done on a cluster with three nodes, shards total is 3. So this problem is only on STAGE, not on DEV since DEV only has 1 node.

We need to test more on cluster with multiple nodes.

**Comment by blairlearn** [comment]
Fixed with commit ea641f25bcfe02f410c159ada5af3dbf070b1560
