### ISSUE TITLE
Implement deployment health check

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/bestbets-api#17]
The deployment script does not currently check whether the API container is successfully running.  This is due a race condition where processing returns to the script after the container is running, but potentially before the API has started.

TODO:
1. Move the curl logic from deploy-stage.sh into a healthcheck script to be included in the API image.
1. Modify the Dockerfile to use the HEALTHCHECK directive, specifying the aforementioned healtcheck script.
1. Check the container's Status property using `docker ps --format {{.Status}}`

**Comment by blairl-nih** [comment]
overtaken by events
