### ISSUE TITLE
Cleanup code cannot differentiate preview indices from live indices

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/bestbets-api#18]
BestBets Index Name needs to separate alias portion from timestamp.  Currently the code builds the best bets index name as <indexname><timestamp>, e.g. bestbets20170213112900.  The issue is that when getting index settings you pass in a query such as bestbets*.  In the case of the live collection, this would result in matching both live and preview indices.

We can just set the alias name to bestbetslive, (low LOE) or update the code to add a _ separator.  I like the latter as it would allow for reuse.

NOTE: this should only be fixed once the cleanup code has been developed completely.

**Comment by blairl-nih** [comment]
Overtaken by events.  We now have separate indices.
