### ISSUE TITLE
index.html loads the petstore swagger document instead of the one for best bets

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/bestbets-api#44]
### Issue description
Accessing /bestbets/v1/index.html leads to an error message as the page attempts to load the sample swagger document from http://petstore.swagger.io instead of the one for best bets. The error occurs because in addition to being the wrong swagger document, it's also being loaded over HTTP onto an HTTPS page.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Navigate to https://webapis.cancer.gov/bestbets/v1/index.html

### What's the expected result?
- An interactive form documenting the API's available functionality.

### What's the actual result?
-Error failing to fetch http://petstore.swagger.io/v2/swagger.json

### Additional details / screenshot
- Accessing https://webapis.cancer.gov/bestbets/v1/ (leaving off the "index.html") works as expected.
- 
![image](https://user-images.githubusercontent.com/21063180/104214012-f4499f00-5404-11eb-8889-1156844f8c0c.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment]
This is flagged as a medium security vulnerability.

**Comment by blairl-nih** [comment]
Closed by 2509c143158d7a53315f3a157b6fbfabcbfabfa6
