### ISSUE TITLE
Enabler: Best Bets Update to .Net 3.1

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/bestbets-api#46]
The Best Bets  API presently uses .Net Core 2.1. [That version is end-of-life on August 21.](https://dotnet.microsoft.com/download/dotnet)

The new long term support version is 3.1 (released May 11).  End-of-life for that version in December of 2022.

The updated API should use [a self-contained runtime](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained).

## Subtaks
- [ ] #49

**Comment by blairl-nih** [comment]
Closed by 2509c143158d7a53315f3a157b6fbfabcbfabfa6
